# Generated by Django 5.0.4 on 2026-03-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Входящие сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('tagline', models.CharField(max_length=200, verbose_name='Слоган')),
                ('about_text', models.TextField(verbose_name='О себе')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pages/avatar/', verbose_name='Аватар')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Местоположение')),
                ('resume_pdf', models.FileField(blank=True, null=True, upload_to='pages/resume/', verbose_name='Резюме PDF')),
                ('cv_data', models.JSONField(blank=True, default=dict, verbose_name='Данные CV (JSON)')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta Description')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.URLField(verbose_name='URL')),
                ('icon_class', models.CharField(help_text='Например: fab fa-github', max_length=50, verbose_name='CSS класс иконки')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='pages.sitesettings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Ссылка соцсети',
                'verbose_name_plural': 'Ссылки соцсетей',
                'ordering': ['order'],
            },
        ),
    ]
