# Generated by Django 6.0.3 on 2026-03-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pages/logo/', verbose_name='Логотип (шапка и подвал)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='pages/avatar/', verbose_name='Аватар (фото на сайте)'),
        ),
    ]
