# Generated by Django 6.0.3 on 2026-03-22 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sitesettings_logo_alter_sitesettings_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('issuer', models.CharField(max_length=100, verbose_name='Выдан')),
                ('year', models.CharField(max_length=10, verbose_name='Год')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/certificates/', verbose_name='Изображение сертификата')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка (опционально)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='pages.sitesettings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['order'],
            },
        ),
    ]
