# Generated by Django 6.0.3 on 2026-03-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pages/about/', verbose_name='Фото на странице «Обо мне»'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='pages/avatar/', verbose_name='Аватар (фото на главной)'),
        ),
    ]
