# Generated by Django 6.0.3 on 2026-03-23 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_sitesettings_about_photo_alter_sitesettings_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('degree', models.CharField(max_length=200, verbose_name='Степень / специальность')),
                ('institution', models.CharField(max_length=200, verbose_name='Учебное заведение')),
                ('period', models.CharField(help_text='Например: 2018 — 2022', max_length=50, verbose_name='Период')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='pages.sitesettings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('period', models.CharField(help_text='Например: 2022 — настоящее время', max_length=50, verbose_name='Период')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='pages.sitesettings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['order'],
            },
        ),
    ]
