# Generated by Django 6.0.3 on 2026-05-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_add_birth_date_education_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Аккаунт Telegram, например @username', max_length=100, null=True, verbose_name='Telegram'),
        ),
    ]
