# Generated by Django 6.0.6 on 2026-06-18 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_add_telegram_username_to_contactmessage'),
        ('portfolio', '0003_add_how_it_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author_name', models.CharField(max_length=100, verbose_name='Имя автора')),
                ('author_position', models.CharField(blank=True, help_text='Например: CEO, Acme Inc. (опционально)', max_length=200, verbose_name='Должность / компания')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='pages/reviews/', verbose_name='Скриншот отзыва')),
                ('text', models.TextField(blank=True, help_text='Опционально — показывается, если нет скриншота', verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, help_text='От 0 до 5. 0 — не показывать звёзды', verbose_name='Оценка (звёзды)')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='Дата отзыва')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('project', models.ForeignKey(blank=True, help_text='Если указан — в карточке появится ссылка на страницу проекта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='portfolio.project', verbose_name='Проект (кейс на сайте)')),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pages.sitesettings', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['order', '-review_date', '-created_at'],
            },
        ),
    ]
