# Generated by Django 5.0.4 on 2026-03-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('mockup_image', models.ImageField(upload_to='portfolio/mockups/', verbose_name='Мокап (обложка)')),
                ('brief_description', models.CharField(max_length=300, verbose_name='Краткое описание')),
                ('task_description', models.TextField(verbose_name='Задача')),
                ('solution_description', models.TextField(verbose_name='Решение')),
                ('result_description', models.TextField(verbose_name='Результат')),
                ('demo_video_url', models.URLField(blank=True, help_text='YouTube или Vimeo embed URL', verbose_name='Ссылка на видео')),
                ('demo_video_file', models.FileField(blank=True, null=True, upload_to='portfolio/videos/', verbose_name='Видео файл')),
                ('source_link', models.URLField(blank=True, verbose_name='Ссылка на исходники')),
                ('live_demo_link', models.URLField(blank=True, verbose_name='Ссылка на демо')),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Избранный')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('color', models.CharField(default='#4A90D9', help_text='HEX цвет, например #4A90D9', max_length=7, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Тег технологии',
                'verbose_name_plural': 'Теги технологий',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='portfolio/screenshots/', verbose_name='Скриншот')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='portfolio.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Скриншот проекта',
                'verbose_name_plural': 'Скриншоты проекта',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.techtag', verbose_name='Технологии'),
        ),
    ]
