# Generated by Django 6.0.3 on 2026-03-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techtag',
            name='logo_key',
            field=models.CharField(blank=True, help_text='Slug для simpleicons.org. Примеры: python, django, fastapi, flask, git, postgresql, docker, nginx, vite, telegram, googlesheets, n8n, javascript, html5, css3', max_length=50, verbose_name='Ключ иконки'),
        ),
    ]
