# Generated by Django 6.0.3 on 2026-03-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_add_techtag_logo_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='how_it_works',
            field=models.TextField(blank=True, verbose_name='Как работает'),
        ),
    ]
